# æœ¬åœ°å±€åŸŸç½‘åœ°å€
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Lan/Lan.list"

# ä¸‹è½½æœåŠ¡
[[rulesets]]
group = "â¬‡ï¸ ä¸‹è½½æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Download/Download.list"

# PTä¸‹è½½
[[rulesets]]
group = "ğŸ…±ï¸ BT/PT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/PrivateTracker/PrivateTracker.list"

# ä»¥ä¸‹æ˜¯å…·ä½“æœåŠ¡
# Netflix
[[rulesets]]
group = "ğŸŒ å…¨çƒæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Netflix/Netflix.list"

# Disney
[[rulesets]]
group = "ğŸŒ å…¨çƒæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Disney/Disney.list"

# Youtube
[[rulesets]]
group = "ğŸŒ å…¨çƒæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube.list"

# YouTubeMusic
[[rulesets]]
group = "ğŸŒ å…¨çƒæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTubeMusic/YouTubeMusic.list"

# AppleMusic
[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AppleMusic/AppleMusic.list"

# AppleTV
[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AppleTV/AppleTV.list"

# BiliBili
[[rulesets]]
group = "ğŸ“½ï¸ Bilibili"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/BiliBili/BiliBili.list"

# Sharon Emby
[[rulesets]]
group = "ğŸ“º Sharon Emby"
ruleset = "https://github.com/stevennight/bypass_rule/raw/refs/heads/main/Rule/Global/SharonEmby/SharonEmby.list"

# TVB
[[rulesets]]
group = "ğŸŒ é¦™æ¸¯æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TVB/TVB.list"

# ViuTV
[[rulesets]]
group = "ğŸŒ é¦™æ¸¯æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ViuTV/ViuTV.list"

# å·´å“ˆå§†ç‰¹
[[rulesets]]
group = "ğŸŒ å°æ¹¾æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Bahamut/Bahamut.list"

# AbemaTV
[[rulesets]]
group = "ğŸŒ æ—¥æœ¬æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AbemaTV/AbemaTV.list"

# Niconico
[[rulesets]]
group = "ğŸŒ æ—¥æœ¬æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Niconico/Niconico.list"

# TVer
[[rulesets]]
group = "ğŸŒ æ—¥æœ¬æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TVer/TVer.list"

# HuluJP
[[rulesets]]
group = "ğŸŒ æ—¥æœ¬æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/HuluJP/HuluJP.list"

# Spotify
[[rulesets]]
group = "ğŸŒ æ—¥æœ¬æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Spotify/Spotify.list"

# NHK
[[rulesets]]
group = "ğŸŒ æ—¥æœ¬æœåŠ¡"
ruleset = "https://github.com/stevennight/bypass_rule/raw/refs/heads/main/Rule/Japan/NHK/NHK.list"

# GitHub
[[rulesets]]
group = "ğŸŒ å…¨çƒæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list"

# OneDrive
[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OneDrive/OneDrive.list"

# Microsoft
[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Microsoft/Microsoft.list"

# Teams
[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Teams/Teams.list"

# MicrosoftEdge
[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/MicrosoftEdge/MicrosoftEdge.list"

# å¿…åº”
[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Bing/Bing.list"

# OpenAI
[[rulesets]]
group = "ğŸŒ ç¾å›½æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI.list"

# Gemini
[[rulesets]]
group = "ğŸŒ ç¾å›½æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Gemini/Gemini.list"

# Claude
[[rulesets]]
group = "ğŸŒ ç¾å›½æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Claude/Claude.list"

# Jetbrains
[[rulesets]]
group = "ğŸŒ ç¾å›½æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Jetbrains/Jetbrains.list"

# Meta AI
[[rulesets]]
group = "ğŸŒ ç¾å›½æœåŠ¡"
ruleset = "https://github.com/stevennight/bypass_rule/raw/refs/heads/main/Rule/Global/MetaAi/MetaAi.list"

# Crunchyroll
[[rulesets]]
group = "ğŸŒ ç¾å›½æœåŠ¡"
ruleset = "https://github.com/stevennight/bypass_rule/raw/refs/heads/main/Rule/America/Crunchyroll/Crunchyroll.list"

# Copilot
[[rulesets]]
group = "ğŸŒ å…¨çƒæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Copilot/Copilot.list"

# OKXäº¤æ˜“æ‰€
[[rulesets]]
group = "ğŸ’° æµ·å¤–é‡‘èæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OKX/OKX.list"

# å¸å®‰
[[rulesets]]
group = "ğŸ’° æµ·å¤–é‡‘èæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Binance/Binance.list"

# PayPal
[[rulesets]]
group = "ğŸ’° æµ·å¤–é‡‘èæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/PayPal/PayPal.list"

# Telegram
[[rulesets]]
group = "ğŸ“² ç”µæŠ¥ä¿¡æ¯"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram.list"

# GlobalMedia
[[rulesets]]
group = "ğŸŒ å…¨çƒæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GlobalMedia/GlobalMedia.list"

# Micu Emby å›½å†…çº¿è·¯
[[rulesets]]
group = "ğŸŒ å›½å†…æœåŠ¡"
ruleset = "https://github.com/stevennight/bypass_rule/raw/refs/heads/main/Rule/China/Micu/Micu.list"

# Micu Emby æµ·å¤–çº¿è·¯
[[rulesets]]
group = "ğŸŒ å…¨çƒæœåŠ¡"
ruleset = "https://github.com/stevennight/bypass_rule/raw/refs/heads/main/Rule/Global/Micu/Micu.list"

# ChinaMedia
[[rulesets]]
group = "ğŸŒ å›½å†…æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ChinaMedia/ChinaMedia.list"

# China
[[rulesets]]
group = "ğŸŒ å›½å†…æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/China/China.list"

# ChinaCDN
[[rulesets]]
group = "ğŸŒ å›½å†…æœåŠ¡"
ruleset = "https://github.com/stevennight/bypass_rule/raw/refs/heads/main/Rule/China/ChinaCDN/ChinaCDN.list"

# ChinaIPs
[[rulesets]]
group = "ğŸŒ å›½å†…æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ChinaIPs/ChinaIPs.list"

# å›½å†…IP
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN"

# æµ·å¤–IP/åŸŸå
[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Proxy/Proxy.list"

# åŠŸèƒ½æ€§
# å»å¹¿å‘Š
[[rulesets]]
group = "â›”ï¸ å¹¿å‘Šæ‹¦æˆª"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AdvertisingLite/AdvertisingLite.list"

# ååŠ«æŒ
[[rulesets]]
group = "ğŸš« è¿è¥åŠ«æŒ"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Hijacking/Hijacking.list"

# éšç§ä¿æŠ¤
[[rulesets]]
group = "ğŸš« è¿è¥åŠ«æŒ"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Privacy/Privacy.list"

# çŸ¥ä¹å¹¿å‘Šæ‹¦æˆª
[[rulesets]]
group = "â›”ï¸ å¹¿å‘Šæ‹¦æˆª"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ZhihuAds/ZhihuAds.list"

# AdGuardSDNSFilter
[[rulesets]]
group = "â›”ï¸ å¹¿å‘Šæ‹¦æˆª"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AdGuardSDNSFilter/AdGuardSDNSFilter.list"

# BlockHttpDNS
[[rulesets]]
group = "ğŸš« è¿è¥åŠ«æŒ"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/BlockHttpDNS/BlockHttpDNS.list"

# å…¨å±€å…œåº•
[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"